name: Upload Website
on:
 push:
   branches:
     - master
jobs:
 Deploy:
   runs-on: ubuntu-latest
   env:
     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
     AWS_CLOUDFRONT_URL: ${{ secrets.AWS_CLOUDFRONT_URL }}
     APP_NAME: ${{ secrets.APPLICATION_NAME }}
   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup node
       uses: actions/setup-node@v2

     - name: Install dependencies
       run: npm install

     - name: Build static file
       run: npm run build

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: us-east-1

     - name: Delete Old Build in S3
       run: aws s3 rm s3://abdul-githubactions --recursive
       
     - name: Update New Build to S3
       run: aws s3 cp --recursive --acl public-read ./build/ s3://abdul-githubactions/  
      
     - name: Update Cloudfront with New-Build
       run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_URL --paths '/*'

     - name: Slack Notification
       uses: act10ns/slack@v1
       with: 
         status: ${{ job.status }}
         channel: '#deployment-alerts'
         message: Deployed $APP_NAME from {{ env.GITHUB_REF_NAME }} branch Successfully
       if: always()   
